title: Richard M. Williams # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Over 25 years of windows server administration experience, & 6 years of software development\automation experience. 
  <br><br>
  <a href="https://www.linkedin.com/in/richmwilliams">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
